name: Megon CSS Minifier
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Combine and Minify CSS
        run: |
          mkdir -p dist/latest
          find src -name "*.css" -type f -exec cat {} + > dist/latest/megon.css
          tr -d '\n' < dist/latest/megon.css | sed 's/  */ /g' | sed 's/ :/:/g' | sed 's/ {/{/g' | sed 's/{ /{/g' | sed 's/ ;/;/g' | sed 's/; /;/g' > dist/latest/megon.min.css

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add dist/
          git commit -m "Auto-minify megon.css" || exit 0
          git push
