name: Megon CSS Build

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install CleanCSS
        run: npm install -g clean-css-cli

      - name: Build CSS
        run: |
          mkdir -p dist/latest

          find src -type f -name "*.css" \
          ! -name "megon.css" \
          | sort \
          | xargs cat > dist/latest/megon.css

          cleancss -o dist/latest/megon.min.css dist/latest/megon.css

      - name: Commit Build Files
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add dist/

          git diff --cached --quiet && exit 0

          git commit -m "Build Megon CSS"
          git push